/**
 * reportCard.js
 * -------------------------------------------------------
 * Renders a structured diagnosis report (diagnosis, severity,
 * specialist, cause, advice, self-care, immediate action, when
 * to seek help) as a clean card — never as raw JSON.
 * Used by the chatbot page when the backend sends a final report.
 * -------------------------------------------------------
 */

const FIELD_LABELS = {
  immediate_action: "Immediate action",
  self_care: "Self-care",
  when_to_seek_help: "When to seek help",
  specialist: "Specialist",
  advice: "Advice",
  cause: "Likely cause",
};

const FIELD_ORDER = [
  "specialist",
  "cause",
  "immediate_action",
  "self_care",
  "advice",
  "when_to_seek_help",
];

function severityClass(severity) {
  const s = (severity || "").toLowerCase();
  if (s.includes("severe") || s.includes("high") || s.includes("emergency")) return "risk";
  if (s.includes("moderate") || s.includes("medium")) return "warn";
  return "ok";
}

export function renderReportCard(report) {
  if (!report) return "";

  const sevClass = severityClass(report.severity);

  const rows = FIELD_ORDER.filter((key) => report[key])
    .map(
      (key) => `
        <div class="report-row">
          <div class="report-row-label">${FIELD_LABELS[key]}</div>
          <div class="report-row-value">${escapeHtml(report[key])}</div>
        </div>`
    )
    .join("");

  return `
    <div class="report-card">
      <div class="report-card-head">
        <div>
          <div class="report-card-eyebrow">Diagnosis</div>
          <div class="report-card-title">${escapeHtml(report.diagnosis || "Not specified")}</div>
        </div>
        ${report.severity ? `<span class="severity-badge severity-${sevClass}">${escapeHtml(report.severity)}</span>` : ""}
      </div>
      ${rows ? `<div class="report-card-body">${rows}</div>` : ""}
      <div class="disclaimer">
        This report is generated by an AI research prototype and is not a medical diagnosis.
        Please consult a licensed doctor for any real health concern.
      </div>
    </div>
  `;
}

function escapeHtml(str) {
  return String(str).replace(/[&<>"']/g, (c) => ({
    "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;",
  }[c]));
}
